# Generated by Django 4.0.4 on 2022-05-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_of_action', models.CharField(max_length=255)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Action_status',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'working'), (2, 'chatting'), (3, 'drinking_coffee'), (4, 'taking_break'), (5, 'helping_colleague')], primary_key=True, serialize=False)),
            ],
        ),
    ]
