# Generated by Django 4.0.4 on 2022-05-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='action.action_status'),
        ),
    ]
