# Generated by Django 4.0.4 on 2022-05-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_action_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='type_of_action',
        ),
    ]
