# Generated by Django 4.0.4 on 2022-05-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_remove_action_type_of_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='action',
            name='date_to',
        ),
        migrations.AddField(
            model_name='action',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='time_from',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='time_to',
            field=models.TimeField(null=True),
        ),
    ]
