# Generated by Django 4.0.4 on 2022-05-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0005_remove_action_date_from_remove_action_date_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[(1, 'working'), (2, 'chatting'), (3, 'drinking_coffee'), (4, 'taking_break'), (5, 'helping_colleague')], default='working', max_length=20),
        ),
        migrations.DeleteModel(
            name='Action_status',
        ),
    ]
